apiVersion: v1
kind: Service
metadata:
  name: hello-netcore-k8s
  labels:
    app: hello-netcore-k8s
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 80
    protocol: TCP
  selector:
    app: hello-netcore-k8s